NDEV-1515: Implement clickhouse scheduler
neonlabsorg/geyser-neon-filter pull request #11
Opened 2023-03-30 08:22 UTC by Deniskore

2023-04-03 17:48 UTC, dk-neon requested changes

2023-04-03 17:48 UTC, dk-neon commented on v2-advanced/clickhouse-scheduler/src/config.rs
> +    pub backoff: Duration,
Maybe it's better to rename to retry_delay?

2023-04-03 17:48 UTC, dk-neon commented on v2-advanced/clickhouse-scheduler/test_config.json
> +        "backoff": "1s"
Rename to `retry_delay`?

2023-04-03 17:48 UTC, dk-neon commented on v2-advanced/clickhouse-scheduler/src/executor.rs
> +                    if retry_fn.await.is_err() {
We should also catch shutdown.changed() here, because this operation can take a while (if there are multiple retries and delays).

2023-04-04 03:31 UTC, Deniskore commented on v2-advanced/clickhouse-scheduler/src/executor.rs
> +        match client.query(q).execute().await {
Done.

2023-04-04 03:31 UTC, Deniskore commented on v2-advanced/clickhouse-scheduler/src/config.rs
> +    pub backoff: Duration,
Done.

2023-04-04 03:31 UTC, Deniskore commented on v2-advanced/clickhouse-scheduler/test_config.json
> +        "backoff": "1s"
Done.

2023-04-04 03:31 UTC, Deniskore commented on v2-advanced/clickhouse-scheduler/src/executor.rs
> +                    if retry_fn.await.is_err() {
Done.

2023-04-04 04:39 UTC, dk-neon approved these changes

2023-04-04 05:00 UTC, merged