WIP: prometheus for scheduler
neonlabsorg/geyser-neon-filter pull request #15
Opened 2023-04-07 18:15 UTC by valiksinev

only base functionality is implemented this commit

2023-04-10 12:38 UTC, Deniskore requested changes
Please also run cargo clippy

```
warning: using `clone` on type `f64` which implements the `Copy` trait
  --> v2-advanced/clickhouse-scheduler/src/executor.rs:71:41
   |
71 |                     metric.min_time.set(measurement_queue.iter().min_by( |a, b| a.total_cmp(b)).unwrap_or(&0_f64).clone());
   |                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: try dereferencing it: `*measurement_queue.iter().min_by( |a, b| a.total_cmp(b)).unwrap_or(&0_f64)`
   |
   = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#clone_on_copy
   = note: `#[warn(clippy::clone_on_copy)]` on by default

warning: using `clone` on type `f64` which implements the `Copy` trait
  --> v2-advanced/clickhouse-scheduler/src/executor.rs:72:41
   |
72 |                     metric.max_time.set(measurement_queue.iter().max_by( |a, b| a.total_cmp(b)).unwrap_or(&0_f64).clone());
   |                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: try dereferencing it: `*measurement_queue.iter().max_by( |a, b| a.total_cmp(b)).unwrap_or(&0_f64)`
   |
   = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#clone_on_copy

warning: unneeded `return` statement
   --> v2-advanced/clickhouse-scheduler/src/executor.rs:115:5
    |
115 |     return None
    |     ^^^^^^^^^^^
    |
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#needless_return
    = note: `#[warn(clippy::needless_return)]` on by default
    = help: remove `return`

warning: redundant clone
  --> v2-advanced/clickhouse-scheduler/src/prometheus.rs:45:72
   |
45 |             registry.register(&errors_name, &errors_name, metric.errors.clone());
note: this value is dropped without further use
  --> v2-advanced/clickhouse-scheduler/src/prometheus.rs:45:59
   |
45 |             registry.register(&errors_name, &errors_name, metric.errors.clone());
   |                                                           ^^^^^^^^^^^^^
   = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#redundant_clone
   = note: `#[warn(clippy::redundant_clone)]` on by default

warning: `clickhouse-scheduler` (bin "clickhouse-scheduler") generated 4 warnings
```

2023-04-10 12:38 UTC, Deniskore commented on v2-advanced/clickhouse-scheduler/Cargo.toml
> +prometheus-client = "0.19.0"
Please update to 0.20.0

2023-04-10 12:38 UTC, Deniskore commented on v2-advanced/clickhouse-scheduler/src/executor.rs
> +        // let metric = metric.clone();
Please remove comment.

2023-04-10 13:16 UTC, valiksinev commented on v2-advanced/clickhouse-scheduler/src/executor.rs
> +        // let metric = metric.clone();
comment removed

2023-04-10 13:17 UTC, valiksinev commented on v2-advanced/clickhouse-scheduler/Cargo.toml
> +prometheus-client = "0.19.0"
version updated

2023-04-11 16:43 UTC, Deniskore approved these changes

2023-04-13 08:32 UTC, merged