Ndev 1767 retention with file
neonlabsorg/geyser-neon-filter pull request #27
Opened 2023-06-14 20:28 UTC by valiksinev

2023-06-15 11:08 UTC, valiksinev commented
> 1. Provide test config file
> 2. Use logger and console output at the same time. You can use fastlog.
> 3. Introduce config path to the config.

config.yaml  is attached
fast_log added
log_file_name added to config

2023-06-15 11:17 UTC, valiksinev commented on v2-advanced/clickhouse-retention/src/client.rs
> +        println!("execution time: {} sec", execution_time.as_secs());
decimal part  - it unnecessary information for this task

2023-06-15 13:12 UTC, valiksinev commented on v2-advanced/clickhouse-retention/src/client.rs
> +        let range = 24000;  // 216000:9 = 24000
added to config

2023-06-15 14:39 UTC, Deniskore requested changes

2023-06-15 14:39 UTC, Deniskore commented on v2-advanced/clickhouse-retention/src/main.rs
> +    info!("Start copiyng to older_account");
Fix typo please.

2023-06-15 14:39 UTC, Deniskore commented on v2-advanced/clickhouse-retention/src/client.rs
> +        let url = config.clickhouse_url.get(id).unwrap();
We can replace it with expect()

2023-06-15 14:39 UTC, Deniskore commented on v2-advanced/clickhouse-retention/src/config.rs
> +        .expect("COPY_PARTITION_OFFSET should be set").parse::<u64>().unwrap();
Please replace unwrap calls with expect.

2023-06-15 14:44 UTC, valiksinev commented on v2-advanced/clickhouse-retention/src/client.rs
> +        let url = config.clickhouse_url.get(id).unwrap();
fixed

2023-06-15 14:48 UTC, valiksinev commented on v2-advanced/clickhouse-retention/src/config.rs
> +        .expect("COPY_PARTITION_OFFSET should be set").parse::<u64>().unwrap();
fixed

2023-06-16 11:48 UTC, Deniskore approved these changes

2023-06-16 11:49 UTC, merged