Implemented graceful shutdown
neonlabsorg/geyser-neon-filter pull request #7
Opened 2023-03-20 08:13 UTC by dk-neon

Also updated workflow in order to prevent message loss in filter.

2023-03-29 06:00 UTC, Deniskore requested changes

2023-03-29 06:00 UTC, Deniskore commented on v1-simple/src/db.rs
> +                    tokio::time::sleep(Duration::from_millis(50)).await;
Let's switch to interval here.

2023-03-29 06:00 UTC, Deniskore commented on v1-simple/src/offset_manager.rs
> +    partitions: HashMap<i32, PartitionOffsetManager>,
Replace with https://docs.rs/ahash/latest/ahash/struct.AHashMap.html please.

2023-03-29 06:00 UTC, Deniskore commented on v1-simple/src/db.rs
> +    let mut shutdown_stream = signal(SignalKind::terminate()).unwrap();
I suggest handling this unwrap.

2023-03-29 06:00 UTC, Deniskore commented on v1-simple/src/consumer.rs
> +    let mut shutdown_stream = signal(SignalKind::terminate()).unwrap();
I suggest handling this unwrap with a good error message.

2023-03-29 06:49 UTC, dk-neon commented on v1-simple/src/offset_manager.rs
> +    partitions: HashMap<i32, PartitionOffsetManager>,
Done.

2023-03-29 06:50 UTC, Deniskore commented on v1-simple/src/db.rs
> +    let mut shutdown_stream = signal(SignalKind::terminate()).unwrap();
@dk-neon Need to think about how not to create a signal handler on every message.

2023-03-29 06:52 UTC, dk-neon commented on v1-simple/src/db.rs
> +    let mut shutdown_stream = signal(SignalKind::terminate()).unwrap();
Done.

2023-03-29 06:52 UTC, dk-neon commented on v1-simple/src/consumer.rs
> +    let mut shutdown_stream = signal(SignalKind::terminate()).unwrap();
Done.

2023-04-03 03:48 UTC, Deniskore commented
@dk-neon Please add new parameter to README.md.

2023-04-03 10:21 UTC, Deniskore approved these changes

2023-04-03 10:40 UTC, merged